server:
  port: 9192

spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      max-age: 3600
      allowed-headers: "*"
      exposed-headers: "X-Get-Header"

  datasource:
    username: hotelbookinguser
    password: hotelbookinguser
    url: jdbc:mysql://localhost:3306/hotel_booking_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

